
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 888
      MYSQL_USER: 888
      MYSQL_PASSWORD: 888
      MYSQL_ROOT_PASSWORD: 888
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/8888/mysql:/var/lib/mysql

  8888:
    image: wordpress
    restart: always
    ports:
      - '52074:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: 888
      WORDPRESS_DB_PASSWORD: 888
      WORDPRESS_DB_NAME: 888
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/8888/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '52075:8080'
    environment:
      TZ: America/Sao_Paulo
