
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 999
      MYSQL_USER: 999
      MYSQL_PASSWORD: 999
      MYSQL_ROOT_PASSWORD: 999
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/9999/mysql:/var/lib/mysql

  9999:
    image: wordpress
    restart: always
    ports:
      - '10236:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: 999
      WORDPRESS_DB_PASSWORD: 999
      WORDPRESS_DB_NAME: 999
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/9999/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '10237:8080'
    environment:
      TZ: America/Sao_Paulo
