
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: aluno
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno
      MYSQL_ROOT_PASSWORD: aluno
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/555/mysql:/var/lib/mysql

  555:
    image: wordpress
    restart: always
    ports:
      - '20439:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: aluno
      WORDPRESS_DB_PASSWORD: aluno
      WORDPRESS_DB_NAME: aluno
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/555/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '20440:8080'
    environment:
      TZ: America/Sao_Paulo
