
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sdfsdf
      MYSQL_USER: terwer
      MYSQL_PASSWORD: sdfsdf
      MYSQL_ROOT_PASSWORD: sdfsdf
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/888/mysql:/var/lib/mysql

  888:
    image: wordpress
    restart: always
    ports:
      - '16029:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: terwer
      WORDPRESS_DB_PASSWORD: sdfsdf
      WORDPRESS_DB_NAME: sdfsdf
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/888/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '16030:8080'
    environment:
      TZ: America/Sao_Paulo
