
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: este
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_PASSWORD: teste
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/777/mysql:/var/lib/mysql

  777:
    image: wordpress
    restart: always
    ports:
      - '21226:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: teste
      WORDPRESS_DB_PASSWORD: teste
      WORDPRESS_DB_NAME: este
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/777/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '21227:8080'
    environment:
      TZ: America/Sao_Paulo
