
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: fff
      MYSQL_USER: fff
      MYSQL_PASSWORD: fff
      MYSQL_ROOT_PASSWORD: fff
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/ffff/mysql:/var/lib/mysql

  ffff:
    image: wordpress
    restart: always
    ports:
      - '65494:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: fff
      WORDPRESS_DB_PASSWORD: fff
      WORDPRESS_DB_NAME: fff
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/ffff/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '65495:8080'
    environment:
      TZ: America/Sao_Paulo
