
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ghfghgh
      MYSQL_USER: hfghfgh
      MYSQL_PASSWORD: ghfgh
      MYSQL_ROOT_PASSWORD: ghfgh
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/fgdffghfh/mysql:/var/lib/mysql

  fgdffghfh:
    image: wordpress
    restart: always
    ports:
      - '38259:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: hfghfgh
      WORDPRESS_DB_PASSWORD: ghfgh
      WORDPRESS_DB_NAME: ghfghgh
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/fgdffghfh/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '38260:8080'
    environment:
      TZ: America/Sao_Paulo
