
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: fghgh
      MYSQL_USER: fghfgh
      MYSQL_PASSWORD: fghg
      MYSQL_ROOT_PASSWORD: fghg
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/gdghgkjhk/mysql:/var/lib/mysql

  gdghgkjhk:
    image: wordpress
    restart: always
    ports:
      - '27323:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: fghfgh
      WORDPRESS_DB_PASSWORD: fghg
      WORDPRESS_DB_NAME: fghgh
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/gdghgkjhk/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '27324:8080'
    environment:
      TZ: America/Sao_Paulo
