
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: gggg
      MYSQL_USER: gggggg
      MYSQL_PASSWORD: ggggg
      MYSQL_ROOT_PASSWORD: ggggg
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/gggggggg/mysql:/var/lib/mysql

  gggggggg:
    image: wordpress
    restart: always
    ports:
      - '59320:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: gggggg
      WORDPRESS_DB_PASSWORD: ggggg
      WORDPRESS_DB_NAME: gggg
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/gggggggg/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '59321:8080'
    environment:
      TZ: America/Sao_Paulo
