
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: hhhhhh
      MYSQL_USER: hhhhh
      MYSQL_PASSWORD: hhhhh
      MYSQL_ROOT_PASSWORD: hhhhh
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/hhhhhhhhhhhh/mysql:/var/lib/mysql

  hhhhhhhhhhhh:
    image: wordpress
    restart: always
    ports:
      - '48177:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: hhhhh
      WORDPRESS_DB_PASSWORD: hhhhh
      WORDPRESS_DB_NAME: hhhhhh
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/hhhhhhhhhhhh/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '48178:8080'
    environment:
      TZ: America/Sao_Paulo
