
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: labtohome
      MYSQL_USER: lab02
      MYSQL_PASSWORD: labmyhome
      MYSQL_ROOT_PASSWORD: labmyhome
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/lab-hmg/mysql:/var/lib/mysql

  lab-hmg:
    image: wordpress
    restart: always
    ports:
      - '54715:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: lab02
      WORDPRESS_DB_PASSWORD: labmyhome
      WORDPRESS_DB_NAME: labtohome
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/lab-hmg/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '54716:8080'
    environment:
      TZ: America/Sao_Paulo
