
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: asdsd
      MYSQL_USER: aa
      MYSQL_PASSWORD: asdsd
      MYSQL_ROOT_PASSWORD: asdsd
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/teste/mysql:/var/lib/mysql

  teste:
    image: wordpress
    restart: always
    ports:
      - '48276:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: aa
      WORDPRESS_DB_PASSWORD: asdsd
      WORDPRESS_DB_NAME: asdsd
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/teste/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '48277:8080'
    environment:
      TZ: America/Sao_Paulo
