
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sss
      MYSQL_USER: sss
      MYSQL_PASSWORD: sss
      MYSQL_ROOT_PASSWORD: sss
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/teste/mysql:/var/lib/mysql

  teste:
    image: wordpress
    restart: always
    ports:
      - '13552:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: sss
      WORDPRESS_DB_PASSWORD: sss
      WORDPRESS_DB_NAME: sss
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/teste/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '13553:8080'
    environment:
      TZ: America/Sao_Paulo
