
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sdsd
      MYSQL_USER: dfdfdf
      MYSQL_PASSWORD: gfgf
      MYSQL_ROOT_PASSWORD: gfgf
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/teste555/mysql:/var/lib/mysql

  teste555:
    image: wordpress
    restart: always
    ports:
      - '52637:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dfdfdf
      WORDPRESS_DB_PASSWORD: gfgf
      WORDPRESS_DB_NAME: sdsd
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/teste555/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '52638:8080'
    environment:
      TZ: America/Sao_Paulo
