
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: teste
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_PASSWORD: teste
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/teste_ssh/mysql:/var/lib/mysql

  teste_ssh:
    image: wordpress
    restart: always
    ports:
      - '41106:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: teste
      WORDPRESS_DB_PASSWORD: teste
      WORDPRESS_DB_NAME: teste
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/teste_ssh/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '41107:8080'
    environment:
      TZ: America/Sao_Paulo
