
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sdfdf
      MYSQL_USER: sdfsdf
      MYSQL_PASSWORD: sdfsdf
      MYSQL_ROOT_PASSWORD: sdfsdf
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/tetedsfgds/mysql:/var/lib/mysql

  tetedsfgds:
    image: wordpress
    restart: always
    ports:
      - '49177:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: sdfsdf
      WORDPRESS_DB_PASSWORD: sdfsdf
      WORDPRESS_DB_NAME: sdfdf
      TZ: America/Sao_Paulo
    volumes:
      - /var/www/wordpress/volumes/tetedsfgds/html:/var/www/html
    depends_on:
      - db  

  adminer:
    image: adminer
    restart: always
    ports:
      - '49178:8080'
    environment:
      TZ: America/Sao_Paulo
