name: Deploy Docker Compose

on:
  push:
    paths:
      - '**/*docker-compose.yml' # Executar quando um arquivo de compose é adicionado ou atualizado

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: SSH Setup
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Copy Docker Compose to Server
        run: scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.REMOTE_PATH }}
      
      - name: SSH into Server and Deploy
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.REMOTE_PATH }} && docker-compose up -d"

  manual-approval:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Manual Approval
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Approve deployment
          file_pattern: .*
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
