name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            git pull origin main
            docker-compose up -d

  manual-approval:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Manual Approval
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Approve deployment
          file_pattern: .*
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
