name: Deploy Docker Compose

on:
  push:
    branches:
      - main  # Altere para a branch desejada

jobs:
  deploy:
    runs-on: ubuntu-latest  # Você pode alterar o sistema operacional aqui, se necessário

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest commit hash
        id: commit_hash
        run: echo "::set-output name=commit_hash::$(git log -1 --pretty=format:'%H')"

      - name: Get file list from last commit
        id: commit_files
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ steps.commit_hash.outputs.commit_hash }} > file_list.txt
          echo "::set-output name=files::$(cat file_list.txt)"

      - name: Find last added file
        id: last_file
        run: |
          IFS=$'\n' read -rd '' -a files <<<"${{ steps.commit_files.outputs.files }}"
          for file in "${files[@]}"; do
            if [[ "$file" == *"-docker-compose.yml" ]]; then
              echo "::set-output name=last_file::$file"
              break
            fi
          done

      - name: Copy file to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /var/www/composes
            cp "${{ steps.last_file.outputs.last_file }}" /var/www/composes/docker-compose.yml

      - name: Docker Compose up on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/composes
            docker-compose up -d
