name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Get commit hash
        run: COMMIT_HASH=$(git rev-parse HEAD)
        id: commit_hash

      - name: Get commit file name
        run: |
          COMMIT_FILE=$(git diff-tree --no-commit-id --name-only -r $COMMIT_HASH | grep 'docker-compose.yml' || echo "")
          echo "COMMIT_FILE=$COMMIT_FILE" >> $GITHUB_ENV

      - name: Rename Docker Compose file
        run: |
          if [[ -n "$COMMIT_FILE" ]]; then
            mv "$COMMIT_FILE" "$COMMIT_HASH-docker-compose.yml"
          fi

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/composes
            git pull origin main
            # Remove o arquivo docker-compose existente no servidor
            rm docker-compose.yml
            # Copia o docker-compose do diretório do repositório
            cp /var/www/composes/"$COMMIT_HASH-docker-compose.yml" docker-compose.yml
            # Inicia o serviço Docker usando o docker-compose do repositório
            docker-compose up -d

  manual-approval:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Manual Approval
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Approve deployment
          file_pattern: .*
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
