name: Deploy Docker Compose

on:
  push:
    branches:
      - main  # Altere para a branch desejada

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Docker Compose file to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /var/www/composes
            FILE=$(find . -name '*-docker-compose.yml' -type f -exec basename {} \;)
            if [ -z "$FILE" ]; then
              echo "No file matching the pattern '*-docker-compose.yml' found in the workspace."
              exit 1
            fi
            cp "$FILE" /var/www/composes/docker-compose.yml
