name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Get latest commit
        run: |
          git pull origin main
          COMMIT_FILE=$(git log -1 --name-only --pretty=format:'' | grep 'docker-compose.yml' | head -n 1)
          echo "COMMIT_FILE=$COMMIT_FILE" >> $GITHUB_ENV

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USER}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd /var/www/composes
            # Copy the latest docker-compose file from the repository directory if it exists
            if [ -n "$COMMIT_FILE" ]; then
              cp "$GITHUB_WORKSPACE/$COMMIT_FILE" docker-compose.yml
            else
              echo "No docker-compose file found in the latest commit."
              exit 1
            fi
            # Execute docker-compose up
            sudo docker-compose up -d
