name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # ajuste de acordo com sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Find latest docker-compose file
        run: |
          latest_file=$(ls -t | grep 'docker-compose.*\.yml' | head -1)
          echo "Latest docker-compose file: $latest_file"
          scp -P ${{ secrets.SSH_PORT }} $latest_file ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/remote/path/to/destination

      - name: SSH Deploy
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /remote/path/to/destination && docker-compose -f $latest_file up -d"
