name: Deploy Docker Compose

on:
  push:
    branches:
      - main  # Altere para a branch desejada

jobs:
  deploy:
    runs-on: ubuntu-latest  # Você pode alterar o sistema operacional aqui, se necessário

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Detect last commit
        id: last_commit
        run: echo "::set-output name=commit_hash::$(git log -1 --pretty=format:'%h')"

      - name: Identify Docker Compose file
        id: docker_compose_file
        run: |
          FILE_CHANGED=$(git diff-tree --no-commit-id --name-only -r ${{ steps.last_commit.outputs.commit_hash }} | grep '\-docker-compose.yml' | tail -n 1)
          echo "::set-output name=docker_compose_file::$FILE_CHANGED"

      - name: Copy Docker Compose file to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /var/www/composes
            cp ${{ steps.docker_compose_file.outputs.docker_compose_file }} /var/www/composes/docker-compose.yml

      - name: Docker Compose up on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/composes/
            docker-compose up -d
