name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Get commit hash
        run: COMMIT_HASH=$(git rev-parse HEAD)
        id: commit_hash

      - name: Get commit file name
        run: |
          COMMIT_FILE=$(git diff-tree --no-commit-id --name-only -r ${{ steps.commit_hash.outputs.COMMIT_HASH }} | grep 'docker-compose.yml' || echo "")
          echo "COMMIT_FILE=$COMMIT_FILE" >> $GITHUB_ENV

      - name: Rename Docker Compose file
        run: |
          if [[ -n "$COMMIT_FILE" ]]; then
            mv "$COMMIT_FILE" "$COMMIT_HASH-docker-compose.yml"
          fi

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 38.50.129.114
          username: uzieljr
          port: 2224
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAslFSlDXhTFQ6bM4nrbzWFdreyWuzHN4K96k9PTumwDAl8B84J+ab
+2+kBgeuHmB0DnHNfQZnTzge1oRAqHYtzZXlPieoqdbUNLqcTOdwrQyB2mLoqswghE0cIA
VfIMKKuq38522huuwXkRpA6yd0R778F27LzMIDrm70xFZiX6m7jr7UWaZ3gIRWubrekT4B
qpmnHtuquRlnC+irxEA4oeQTSqtIpDM90btAyn9fQTCASSKxPQfYBgEXR0fWXgGMCy2k1v
s+2kxvh/u8960rqtxgq0u3KeeVDddHe2V2kqTZ/RFFEecxdBxgFJCSVbaXDl6oLGJsenq2
500T52cumL26fo5uiFboS3xBRvPtMWNQ7oDcFlX8ZHizb1qhRNZcsVl7e6a8sw9az6qPLc
4TgpBFX7J1srbH/Nftkrbxc2V82WQMae243mxCaaHrhe7EHksPPC+Z0QusMjHEZavRy9oT
0iYGsnX+BVkVcTs91hVxSPjI0KZ8EvCQ3l7eExWcPP7UiiHDFhFpGfLs3YwSMQcL2hwNoZ
C1CexO/Mg8R6nPeLGOlEX1RJDHWurFUuPMI2E3my82WIggBm7aTmRK01jeNYlLs2frBlPX
RgE8xe7yDawlAIjxNqK8OLtrWmao8q7+s6pNkfh4QQo8Rd6u0aCASJDxz2/m9uIDc0fhzC
kAAAdQA9oyGgPaMhoAAAAHc3NoLXJzYQAAAgEAslFSlDXhTFQ6bM4nrbzWFdreyWuzHN4K
96k9PTumwDAl8B84J+ab+2+kBgeuHmB0DnHNfQZnTzge1oRAqHYtzZXlPieoqdbUNLqcTO
dwrQyB2mLoqswghE0cIAVfIMKKuq38522huuwXkRpA6yd0R778F27LzMIDrm70xFZiX6m7
jr7UWaZ3gIRWubrekT4BqpmnHtuquRlnC+irxEA4oeQTSqtIpDM90btAyn9fQTCASSKxPQ
fYBgEXR0fWXgGMCy2k1vs+2kxvh/u8960rqtxgq0u3KeeVDddHe2V2kqTZ/RFFEecxdBxg
FJCSVbaXDl6oLGJsenq2500T52cumL26fo5uiFboS3xBRvPtMWNQ7oDcFlX8ZHizb1qhRN
ZcsVl7e6a8sw9az6qPLc4TgpBFX7J1srbH/Nftkrbxc2V82WQMae243mxCaaHrhe7EHksP
PC+Z0QusMjHEZavRy9oT0iYGsnX+BVkVcTs91hVxSPjI0KZ8EvCQ3l7eExWcPP7UiiHDFh
FpGfLs3YwSMQcL2hwNoZC1CexO/Mg8R6nPeLGOlEX1RJDHWurFUuPMI2E3my82WIggBm7a
TmRK01jeNYlLs2frBlPXRgE8xe7yDawlAIjxNqK8OLtrWmao8q7+s6pNkfh4QQo8Rd6u0a
CASJDxz2/m9uIDc0fhzCkAAAADAQABAAACAFRfynU6sWpOiH6nZXr92UbqE3S3Mz87iXD6
cXGh4hsaLTlbbFTk93WXs8Luq2LQPNoA2zyHZSbE5UKXvYh4st+OR7SLS3Fhp3NzwTVaZa
RcQK03E+SNRe2UFvTH1eVIaCBA52QSKe6qe9Q62fDq8EhqhBoKYQB35QoKkmK8hTvCsm6u
uQfajr0O4YJse5e6AUvZ/IvLYRLIhEvMQkpQIPvpUX+JYIvheyTcN6IZdtb/vhPdCIRaS8
s7hOpDgZllngBEDrVymKDufe+YHCgNlpX4RP2IjBiV7Z9o9/fZYKuuuT7Xhxkbjfjk3Eme
xr8r8HnqLCUkRTQHELiNbheWaSMtyDR9zUVLfa5QVY8OE9FJpd0uJXM3Bt+ld4w++7NmUI
YmSRsRYi0KbAG1Lepa61yyEylD9dGUAkrc15ut+mkRyo0VrT3GL4Q+rlcF61+Vt9cxZzk3
TaTOs8t/Ah5Y/aEt3B1TUobLFLkhuBsWQ4kl/g1APYdQNL3bgR+zYKaokux2khSZeFVe4q
VUMU4GaWTPTdfuIGcv6qQnvZFfn+p0nGxryBDS/mUrbt4P74+3bo5q4kc3JnhRm4F3LJmc
4xkqVDoUniGwj13k7HsRLXca7x+/EXqUhiKYsVDqsp9BS843Ye7drZHjmPVzabzo23/8XC
warMJzxcbktBfV4p6JAAABAG6SwXonyF1cChbVn7aqHx6HYEKdtuem/SUF43X4ddEcPm2j
MPeThLQVStul+PZZkQYUt0217TRzNqifniCqS3h6CtLzbJIwNjTru+Q68Fpl0oJUB/vItl
Gs6oVwCqkMxQVmP8ZGYjPE8bqS+ofHmy39K2CtjJR208tHloIksltCCk5o6n8Kt06nZBRA
MfqVM8N+vXkG3mGuVM6BaCIy/k/ybQ7AZnsLJQagtUis7koAaE2VeQXh9HGmTLPigvnWwr
5c5vsSN7lXEBFTst8guOWYa5NN8pV7FT9duPS7dfJ8yzAepITwV5zeFhL1hgpJ7qYGRSAh
esXeTnEeSFNedpcAAAEBAOolyWbgYeK0BuyPnf+gSMi6p7HMeaOGXLBN0vuOaEiCG+Xx8I
zOuyqc30KviUj7diRMRxJQMWpkW2vzMtgAgx23oxpzESNqHM2S2PuhTpvkNg+SXwIONwpS
uTrdpDsmH2Fy+flvVUG8ntr4XQ+YUyawndTa4QLCdEQOWiVw49cO7lVoPbuOWosrIN0Tlg
b2vXQcRWAsI9P6mf5NRc+NubyQpdH/I+1NB1tgx5CKFDAKtRO0Rg96SNcVZnjpIBAcAdPV
bkK03DmSv4nX46fmPmKuAs21OZO391MvwmIwi8WoNcQOVO7+zMNnNA2D3qyKp+VSqru5Ae
5+V3REaI01+XsAAAEBAML1qCTZdqP+sR6lQ/G3sHBCpH21AY7Dk3pXKo7bO8WUFC56jpCE
MlY6gxPzyiha52jBLfb8AC9yYk7h0ZFSuTLas69m5PSIGERVd9CvtkyfLWLHr5IbA3T4PR
9n022ALs/Lbrlt/K9p3dh3jSRgayk1G+Pk5FC5jaH3xCqhQmMC436Od1S/EdD4R3SIcNDY
2nJv7QA7mKWuPDK+Uy/ROfcHcB7XmkItCL0aSIkPJb8DgiMKnwfx9Pn4noTGyo7sJbq/uz
MJ5txPePaGLa6tjjtDC9MuwrK2UusyXbbdxOecX3C1TxDt2wIoJARFv9qdNpgf2/TAGXeh
5KvJJF7iRasAAAAUdXppZWxqckB5YWhvby5jb20uYnIBAgMEBQYH
-----END OPENSSH PRIVATE KEY-----
          script: |
            cd /var/www/composes
            git pull origin main
            # Remove o arquivo docker-compose existente no servidor
            rm docker-compose.yml
            # Copia o docker-compose do diretório do repositório
            cp /var/www/composes/${{ steps.commit_hash.outputs.COMMIT_HASH }}-docker-compose.yml docker-compose.yml
            # Inicia o serviço Docker usando o docker-compose do repositório
            docker-compose up -d

  manual-approval:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Manual Approval
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Approve deployment
          file_pattern: .*
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
