name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find latest YAML file
        id: find_yaml
        run: |
          latest_yaml=$(ls -t | grep .yml | head -1)
          echo "::set-output name=filename::${latest_yaml}"

      - name: Copy YAML file to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/composes
            cp "${{ steps.find_yaml.outputs.filename }}" docker-compose.yml

      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/composes
            docker-compose up -d
