name: Deploy Último Arquivo

on:
  push:
    branches:
      - main  # ajuste conforme sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Identificar último arquivo commitado
        run: |
          LAST_FILE=$(git diff-tree --no-commit-id --name-only -r HEAD | head -n 1)
          echo "Último arquivo commitado: $LAST_FILE"

      - name: Copiar Último Arquivo para o Servidor Remoto
        run: scp -P ${{ secrets.SSH_PORT }} $LAST_FILE ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/composes/

      - name: Executar docker-compose up -d no servidor remoto
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/composes/ && docker-compose up -d"
