name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Get commit hash
        run: COMMIT_HASH=$(git rev-parse HEAD)
        id: commit_hash

      - name: Get commit file name
        run: |
          COMMIT_FILE=$(git diff-tree --no-commit-id --name-only -r ${{ steps.commit_hash.outputs.COMMIT_HASH }} | grep 'docker-compose.yml' || echo "")
          echo "COMMIT_FILE=$COMMIT_FILE" >> $GITHUB_ENV

      - name: Rename Docker Compose file
        run: |
          if [[ -n "$COMMIT_FILE" ]]; then
            mv "$COMMIT_FILE" "$COMMIT_HASH-docker-compose.yml"
          fi

      - name: Clone repository if not exists
        run: |
          if [[ ! -d "/var/www/composes/.git" ]]; then
            git clone https://github.com/uzieljr/lab-wp-automation.git /var/www/composes
          fi

      - name: Make directory valid
        run: cd /var/www/composes

      - name: Create Docker Compose file if not exists
        run: |
          if [[ ! -f "/var/www/composes/docker-compose.yml" ]]; then
            echo "Creating docker-compose.yml with content of last commit..."
            git show $(git log --format="%H" -n 1) | grep -vE '^(commit [0-9a-f]{40}|Author:|Date:)' > /var/www/composes/docker-compose.yml
          fi

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USER}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd /var/www/composes
            git pull origin main
            # Remove o arquivo docker-compose existente no servidor, se existir
            if [ -f "docker-compose.yml" ]; then
              rm docker-compose.yml
            fi
            # Copia o docker-compose do diretório do repositório
            cp /var/www/composes/${{ steps.commit_hash.outputs.COMMIT_HASH }}-docker-compose.yml docker-compose.yml
            # Inicia o serviço Docker usando o docker-compose do repositório
            docker-compose up -d
