name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Get commit hash
        run: COMMIT_HASH=$(git rev-parse HEAD)
        id: commit_hash

      - name: Get commit file name
        run: |
          COMMIT_FILE=$(git diff-tree --no-commit-id --name-only -r ${{ steps.commit_hash.outputs.COMMIT_HASH }} | grep 'docker-compose.yml' || echo "")
          echo "COMMIT_FILE=$COMMIT_FILE" >> $GITHUB_ENV

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: SSH into Server and Deploy
        id: ssh_deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USER}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd /var/www/composes
            # Copia o docker-compose do diretório do repositório
            cp /github/workspace/$COMMIT_FILE docker-compose.yml
            # Inicia o serviço Docker usando o docker-compose do repositório
            docker-compose up -d

  manual-approval:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Manual Approval
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Approve deployment
          file_pattern: .*
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
